name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build Phase: Build the Docker image from the Dockerfile
      - name: Build Docker Image
        run: docker build -t my-docker-app:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Rebuild the image
      - name: Build Docker Image
        run: docker build -t my-docker-app:latest .
      
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Tag Docker Image
        run: docker tag my-docker-app:latest ala*****/my-docker-app:latest
      
      - name: Push Docker Image
        run: docker push ala*****/my-docker-app:latest
